name: Students API Pipeline

on:
  push:
    branch: main

jobs:
  hello:
    runs-on: windows-latest

    steps:
      - name: Say Hello
        run: echo "Hello World"

   listing:
    runs-on:  windows-latest

    steps:
        uses: actions/checkout@v2
        name: Show the directory
        run: ls
      - name: show the index.ts
        run: cat index.ts

  