name: Students API Pipeline


on:
  push:
    branches:
      - master
jobs:
  heroku-deploy:
    runs-on: [windows-latest]
    steps:
    - uses: actions/checkout@master
    - uses: akhileshns/heroku-deploy@v3.12.12
    - name: Login to Heroku
      env: 
        HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
      run: heroku container:login
    - name: Build and Push
      env: 
        HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
      run: heroku container:push -a e-comanda web
    - name: Release
      env:
         HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
      run: heroku container:release -a e-comanda web

     
         


          

          




  