name: Students API Pipeline
on:
  push:
    branch: main
jobs:
  dependencies:
    runs-on: windows-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@octocat'
      - run: npm install

  Test:
      runs-on: windows-latest 
      steps:
        - uses: actions/checkout@v2
        - run: npm install --save-dev jest
        - run: npm run test
  
  build:
      runs-on: windows-latest 
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
        - run: npm ci
        - run: npm run build

  listing_paste_dist:
        runs-on: windows-latest 
        steps:
        - uses: actions/checkout@v2
        - run: ls
