name: Students API Pipeline

on:
  push:
    branch: main

jobs:
    listing:
    name: Execute npm install
    runs-on:  windows-latest


    steps:
        uses: actions/checkout@v2
        name: npm install
        run: npm install
  